services:
  api:
    image: api:latest
    container_name: thehoster-app-api-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../api:/var/www/html
      - ../api/vendor:/var/www/html/vendor
    ports:
      - "8001:80"
    networks:
      - hoster-db_hoster_network_test
    environment:
      DB_HOST: 10.0.2.4   # IP privada de la VM donde corre MySQL
      DB_PORT: 3307       # Puerto expuesto en la VM
      DB_USER: thehoster_test
      DB_PASSWORD: w2449daHK-n2T
      DB_DATABASE: hoster_db
      QUEUE_CONNECTION: redis
      APP_ENV: production
      
networks:
  hoster-db_hoster_network_test:
    external: true
