version: '3'
services:
  # Contenedor principal para Laravel con Apache
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:latest
    container_name: thehoster-app-api-backend
    restart: always
    volumes:
      - ../api:/var/www/html
      - ../api/vendor:/var/www/html/vendor
    ports:
      - "8001:80"
    networks:
      - hoster-db_hoster_network_test
    environment:
      DB_HOST: 10.0.2.4
      DB_PORT: 3307
      DB_USER: thehoster_test
      DB_PASSWORD: w2449daHK-n2T
      DB_DATABASE: hoster_db
    command: ["apache2-foreground"]

  # Contenedor dedicado para cron jobs
  cron:
    image: api:latest
    container_name: thehoster-app-cron
    depends_on:
      - api
    networks:
      - hoster-db_hoster_network_test
    environment:
      DB_HOST: 10.0.2.4
      DB_PORT: 3307
      DB_USER: thehoster_test
      DB_PASSWORD: w2449daHK-n2T
      DB_DATABASE: hoster_db
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

  # Contenedor dedicado para workers de Laravel
  worker:
    image: api:latest
    container_name: thehoster-app-worker
    depends_on:
      - api
    networks:
      - hoster-db_hoster_network_test
    environment:
      DB_HOST: 10.0.2.4
      DB_PORT: 3307
      DB_USER: thehoster_test
      DB_PASSWORD: w2449daHK-n2T
      DB_DATABASE: hoster_db
    command: ["php", "/var/www/html/artisan", "queue:work", "--sleep=3", "--tries=3"]

networks:
  hoster-db_hoster_network_test:
    external: true
